/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as MatchRouteImport } from './routes/match'
import { Route as NepalRouteImport } from './routes/nepal'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as TreksRouteImport } from './routes/treks'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsBhutanRouteImport } from './routes/destinations.bhutan'
import { Route as DestinationsTibetRouteImport } from './routes/destinations.tibet'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as TreksIndexRouteImport } from './routes/treks.index'
import { Route as TreksSlugRouteImport } from './routes/treks.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const NepalRoute = NepalRouteImport.update({
  id: '/nepal',
  path: '/nepal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const TreksRoute = TreksRouteImport.update({
  id: '/treks',
  path: '/treks',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsBhutanRoute = DestinationsBhutanRouteImport.update({
  id: '/destinations/bhutan',
  path: '/destinations/bhutan',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsTibetRoute = DestinationsTibetRouteImport.update({
  id: '/destinations/tibet',
  path: '/destinations/tibet',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/experiences/$slug',
  path: '/experiences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const TreksIndexRoute = TreksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreksRoute,
} as any)
const TreksSlugRoute = TreksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/match': typeof MatchRoute
  '/nepal': typeof NepalRoute
  '/profile': typeof ProfileRoute
  '/quote': typeof QuoteRoute
  '/treks': typeof TreksRouteWithChildren
  '/destinations/bhutan': typeof DestinationsBhutanRoute
  '/destinations/tibet': typeof DestinationsTibetRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/treks/$slug': typeof TreksSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/treks/': typeof TreksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/match': typeof MatchRoute
  '/nepal': typeof NepalRoute
  '/profile': typeof ProfileRoute
  '/quote': typeof QuoteRoute
  '/destinations/bhutan': typeof DestinationsBhutanRoute
  '/destinations/tibet': typeof DestinationsTibetRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/treks/$slug': typeof TreksSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/treks': typeof TreksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/match': typeof MatchRoute
  '/nepal': typeof NepalRoute
  '/profile': typeof ProfileRoute
  '/quote': typeof QuoteRoute
  '/treks': typeof TreksRouteWithChildren
  '/destinations/bhutan': typeof DestinationsBhutanRoute
  '/destinations/tibet': typeof DestinationsTibetRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/treks/$slug': typeof TreksSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/treks/': typeof TreksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/knowledge'
    | '/match'
    | '/nepal'
    | '/profile'
    | '/quote'
    | '/treks'
    | '/destinations/bhutan'
    | '/destinations/tibet'
    | '/experiences/$slug'
    | '/knowledge/$slug'
    | '/treks/$slug'
    | '/destinations/'
    | '/knowledge/'
    | '/treks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/match'
    | '/nepal'
    | '/profile'
    | '/quote'
    | '/destinations/bhutan'
    | '/destinations/tibet'
    | '/experiences/$slug'
    | '/knowledge/$slug'
    | '/treks/$slug'
    | '/destinations'
    | '/knowledge'
    | '/treks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/knowledge'
    | '/match'
    | '/nepal'
    | '/profile'
    | '/quote'
    | '/treks'
    | '/destinations/bhutan'
    | '/destinations/tibet'
    | '/experiences/$slug'
    | '/knowledge/$slug'
    | '/treks/$slug'
    | '/destinations/'
    | '/knowledge/'
    | '/treks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  MatchRoute: typeof MatchRoute
  NepalRoute: typeof NepalRoute
  ProfileRoute: typeof ProfileRoute
  QuoteRoute: typeof QuoteRoute
  TreksRoute: typeof TreksRouteWithChildren
  DestinationsBhutanRoute: typeof DestinationsBhutanRoute
  DestinationsTibetRoute: typeof DestinationsTibetRoute
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nepal': {
      id: '/nepal'
      path: '/nepal'
      fullPath: '/nepal'
      preLoaderRoute: typeof NepalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treks': {
      id: '/treks'
      path: '/treks'
      fullPath: '/treks'
      preLoaderRoute: typeof TreksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/bhutan': {
      id: '/destinations/bhutan'
      path: '/destinations/bhutan'
      fullPath: '/destinations/bhutan'
      preLoaderRoute: typeof DestinationsBhutanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/tibet': {
      id: '/destinations/tibet'
      path: '/destinations/tibet'
      fullPath: '/destinations/tibet'
      preLoaderRoute: typeof DestinationsTibetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/experiences/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/treks/': {
      id: '/treks/'
      path: '/'
      fullPath: '/treks/'
      preLoaderRoute: typeof TreksIndexRouteImport
      parentRoute: typeof TreksRoute
    }
    '/treks/$slug': {
      id: '/treks/$slug'
      path: '/$slug'
      fullPath: '/treks/$slug'
      preLoaderRoute: typeof TreksSlugRouteImport
      parentRoute: typeof TreksRoute
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface TreksRouteChildren {
  TreksSlugRoute: typeof TreksSlugRoute
  TreksIndexRoute: typeof TreksIndexRoute
}

const TreksRouteChildren: TreksRouteChildren = {
  TreksSlugRoute: TreksSlugRoute,
  TreksIndexRoute: TreksIndexRoute,
}

const TreksRouteWithChildren = TreksRoute._addFileChildren(TreksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  MatchRoute: MatchRoute,
  NepalRoute: NepalRoute,
  ProfileRoute: ProfileRoute,
  QuoteRoute: QuoteRoute,
  TreksRoute: TreksRouteWithChildren,
  DestinationsBhutanRoute: DestinationsBhutanRoute,
  DestinationsTibetRoute: DestinationsTibetRoute,
  ExperiencesSlugRoute: ExperiencesSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
